#!/bin/bash
source "$HOME/.cache/wal/colors.sh"

cat > "$HOME/.cache/wal/colors-rofi.rasi" <<EOL
* {
    background:     ${color0};
    background-alt: ${color1};
    foreground:     ${foreground};
    selected:       ${color4};
    active:         ${color2};
    urgent:         ${color3};
}
EOL
