# ================================================
# AUTOSTART - Applications au démarrage
# ================================================

# Scripts personnalisés
exec-once = swww-daemon
exec-once = $scripts/updateWallpaper
exec-once = $scripts/initWaybar
exec-once = $scripts/initSyncthing
exec-once = $scripts/xdgdesktop
exec-once = $scripts/gtkthemes
exec-once = $scripts/lock.sh

# Services système
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = swww-daemon
exec-once = mako
