# ================================================
# ENVIRONMENT - Variables d'environnement
# ================================================

# Curseur
env = XCURSOR_SIZE,18
env = XCURSOR_THEME,WhiteSur-cursors

# GTK Theme (IMPORTANT pour mode dark)
env = GTK_THEME,WhiteSur-Dark

# Wayland
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# XDG
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# NVIDIA (mode actuel)
env = WLR_DRM_DEVICES,/dev/dri/card1
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

# Intel iGPU (pour économie d'énergie - à utiliser à la place)
#env = WLR_DRM_DEVICES,/dev/dri/card0
