# ==========================================
# PROFIL: INTEL iGPU @ 60Hz
# ==========================================

# Variables d'environnement Intel
env = WLR_DRM_DEVICES,/dev/dri/card0

# Moniteur @ 60Hz (change DP-1 par ton écran)
monitor=DP-1,preferred,auto,1,vrr,60

# Désactiver NVIDIA
# (pas de variables NVIDIA)
