--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lamb/Wallpapers/915988.png"

-- Special
background="#301a28"
foreground="#f5edde"
cursor="#f5edde"

-- Colors
color0="#301a28"
color1="#9E738D"
color2="#AE979E"
color3="#DBB299"
color4="#FBCF8F"
color5="#F6DBB3"
color6="#D2B5C5"
color7="#f5edde"
color8="#aba59b"
color9="#9E738D"
color10="#AE979E"
color11="#DBB299"
color12="#FBCF8F"
color13="#F6DBB3"
color14="#D2B5C5"
color15="#f5edde"
