[colors]
background = '#0d06108e'
black = '#0d0610'
blue = '#E8E63F'
cursor = '#c2c0c3'
cyan = '#9A906D'
foreground = '#c2c0c3'
green = '#4D8699'
magenta = '#A8AB92'
red = '#B9C2A9'
tabs = '#c2c0c3'
tabs-active = '#DDD3B1'
white = '#c2c0c3'
yellow = '#c2c0c3'
dim-black = '#0d06108e'
dim-blue = '#E8E63F8e'
dim-cyan = '#9A906D8e'
dim-foreground = '#c2c0c38e'
dim-green = '#4D86998e'
dim-magenta = '#A8AB928e'
dim-red = '#B9C2A98e'
dim-white = '#DDD3B18e'
dim-yellow = '#c2c0c38e'
light-black = '#E8E63F'
light-blue = '#9A906D'
light-cyan = '#4D8699'
light-foreground = '#A8AB92'
light-green = '#B9C2A9'
light-magenta = '#DDD3B1'
light-red = '#c2c0c3'
light-white = '#E8E63F'
light-yellow = '#9A906D'
