[Colors:View]
BackgroundNormal=#301a28
ForegroundNormal=#f5edde
BackgroundAlternate=#301a28

[Colors:Selection]
BackgroundNormal=#9E738D
ForegroundNormal=#301a28

[Colors:Window]
BackgroundNormal=#301a28
ForegroundNormal=#f5edde
