foreground   #f5edde
background   #301a28
cursor       #f5edde

color0       #301a28
color8       #aba59b
color1       #9E738D
color9       #9E738D
color2       #AE979E
color10      #AE979E
color3       #DBB299
color11      #DBB299
color4       #FBCF8F
color12      #FBCF8F
color5       #F6DBB3
color13      #F6DBB3
color6       #D2B5C5
color14      #D2B5C5
color7       #f5edde
color15      #f5edde
