--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lamb/Wallpapers/Wallpaper/wallpapersedgerunners2.jpg"

-- Special
background="#0d0610"
foreground="#c2c0c3"
cursor="#c2c0c3"

-- Colors
color0="#0d0610"
color1="#E8E63F"
color2="#9A906D"
color3="#4D8699"
color4="#A8AB92"
color5="#B9C2A9"
color6="#DDD3B1"
color7="#c2c0c3"
color8="#635669"
color9="#E8E63F"
color10="#9A906D"
color11="#4D8699"
color12="#A8AB92"
color13="#B9C2A9"
color14="#DDD3B1"
color15="#c2c0c3"
