# Shell variables
# Generated by 'wal'
wallpaper='/home/lamb/Wallpapers/915988.png'

# Special
background='#301a28'
foreground='#f5edde'
cursor='#f5edde'

# Colors
color0='#301a28'
color1='#9E738D'
color2='#AE979E'
color3='#DBB299'
color4='#FBCF8F'
color5='#F6DBB3'
color6='#D2B5C5'
color7='#f5edde'
color8='#aba59b'
color9='#9E738D'
color10='#AE979E'
color11='#DBB299'
color12='#FBCF8F'
color13='#F6DBB3'
color14='#D2B5C5'
color15='#f5edde'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
