# pywal theme for ghostty

background = 0d0610
foreground = c2c0c3
cursor-color = c2c0c3
selection-background = c2c0c3
selection-foreground = 0d0610

palette = 0=#0d0610
palette = 1=#E8E63F
palette = 2=#9A906D
palette = 3=#4D8699
palette = 4=#A8AB92
palette = 5=#B9C2A9
palette = 6=#DDD3B1
palette = 7=#c2c0c3
palette = 8=#635669
palette = 9=#E8E63F
palette = 10=#9A906D
palette = 11=#4D8699
palette = 12=#A8AB92
palette = 13=#B9C2A9
palette = 14=#DDD3B1
palette = 15=#c2c0c3
