[Colors:View]
BackgroundNormal={background}
ForegroundNormal={foreground}
BackgroundAlternate={color0}

[Colors:Selection]
BackgroundNormal={color1}
ForegroundNormal={background}

[Colors:Window]
BackgroundNormal={background}
ForegroundNormal={foreground}
